### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by lipisak** [F0rce/ace#17]
Hi @F0rce,
We have upgraded to the new version 1.2.3 with Vaadin 14.5.6. Everything works but search. When I press CMD+F javascript error is thrown that 

```
GET http://localhost:8091/ace-builds/src-min-noconflict/ext-searchbox.js net::ERR_ABORTED 404
```

Could it be related with the last change (make baseUrl relative?). Themes and modes works good and from what I see they are "loaded" from compiled bundle, but this extension is loaded directly not from bundle...

Thx
JS

**Comment by F0rce** [comment]
Hi @lipisak,

this is pretty sure my bad 100 %. Due to the big size the src-min-noconfict & the src-noconflict directorys had, I removed the src-noconflict (which is not needed to be in the frontend directory) and I cleared most of the not needed files in src-min-noconflict. Pretty sure I accidentely deleted the ext-searchbox.js file. I will check it out surely and will build a hotfix as fast as possible. 

Sorry for that inconvenience

Already on it :)

David

**Comment by F0rce** [comment]
Already fixed it and building the new version. Should be availible as version 1.2.4 on the directory in aprox. 25-30 minutes

**Comment by F0rce** [comment]
and obviously sorry for the inconvenience

**Comment by lipisak** [comment]
It's ok... thank you for quick response...

**Comment by F0rce** [comment]
https://vaadin.com/directory/component/ace/1.2.4 --> could take some minutes to be availible via maven
