### ISSUE TITLE
Value is not returned back to server

### ISSUE THREAD

**Issue by lipisak** [F0rce/ace#9]
Hi @F0rce,
I updated to the new 1.2.0 version. UI built up correctly and the component showed up correctly. But I don't get the value from client back to server (doesn't matter if it is connected to binder or not).

Could you please check it up?

Thank you
J

**Comment by F0rce** [comment]
Hello @lipisak,

the value is not binded. It is synced when the editor is blurred (if you didnt knew already).

I'm currently working on some new methods for the Editor so I will surely try it now. But as far as I can see in the web-console the event is sent normally from the frontend and the listeners seem to work.

Will investigate it shortly and update you.

David

**Comment by F0rce** [comment]
You were right, when implementing the changes in #3 I removed a line because I thought I didnt need it. But as far as I can see, it doenst update the value of the editor anymore... What a dumb mistake of mine.

v1.2.0 will not be availible anymore due to this error.

Thanks for showing me, working on a hotfix

**Comment by F0rce** [comment]
I fixed it locally and will publish a hotfix / replace the current version with the fix later today. sorry for the inconvenience...

**Comment by lipisak** [comment]
Wow that was quick...thank you...This time I will test it locally, as we always discover this in production. I know - not a good approach.

**Comment by F0rce** [comment]
fixed everything https://vaadin.com/directory/component/ace/1.2.1
